### ISSUE TITLE
subroutine .dll file

### ISSUE THREAD

**Issue by tygao** [CCSI-Toolset/MEA_ssm#12]
Solid work!
I am wondering is there a chance for you to share the subroutine .dll file? 

Thanks!

**Comment by ksbeattie** [comment]
The ccsi10.dll file is there in the [releases](https://github.com/CCSI-Toolset/MEA_ssm/releases) page.  Or do you mean a different .dll file?

**Comment by tygao** [comment]
Thank you! This is it. Sorry I cloned the repo directly and didn't find it there.

Tianyu

**Comment by ksbeattie** [comment]
btw, the instructions on how to build this DLL for yourself should be in the documentation.
