### ISSUE TITLE
Add dll consistent with Aspen V11 (new release of MEA_ssm)

### ISSUE THREAD

**Issue by jmorgan29** [CCSI-Toolset/MEA_ssm#15]
The most recent release of this model contains a pre-built dll file with compiled Fortran user models that works when running the model in Aspen V10. However, starting with V11, Aspen Plus is now compiled as a 64-bit program and user models must also be compiled as 64-bit code. Therefore, the existing dll attached to the release will not work for Aspen V11. Instructions are provided in a version-independent manner so that the user can create their own dll, provided that they have access to a Fortran compiler.  It is recommended that the V11 compatible dll file (which I have already built and tested) be attached to an upcoming release in order to accommodate users of the newer version of Aspen who do not have a Fortran compiler and/or desire to work directly with the Fortran code to create the dll. The new dll file built for Aspen V11 is expected to work with newer versions of Aspen (V11.1 and V12), although this has not been verified.

**Comment by ksbeattie** [comment]
@jmorgan29, I can attach a new .dll file to the current release.  Or do you think this should be part of a new release (perhaps with clearer documentation?).

**Comment by jmorgan29** [comment]
@ksbeattie, I would recommend creating a new release (probably called 3.2.0) in which the both dll files are available and the documentation is updated to indicate that both versions V10 and V11 are now supported. The Aspen .bkp file should not require any changes. I should be able to make this update before the end of January.

**Comment by ksbeattie** [comment]
Fixed with PR #16
