### ISSUE TITLE
UNABLE TO RUN THE SIMULATION

### ISSUE THREAD

**Issue by BORE2021** [CCSI-Toolset/MEA_ssm#22]
Dear author, first, thank you for sharing this nice work with us.

I am using Aspen Plus V11, I have tried to run the simulation, but the process was unable to proceed displaying the following error message (See attached picture). I would really appreciate if you can help me fix that issue. Thank you for your time and comprehension.

![PROBLEM_MEA-GITHUB](https://user-images.githubusercontent.com/84260480/203911269-9bbea197-7ac7-4a9c-a078-4dec145d82c0.png)

**Comment by ksbeattie** [comment]
Hello, Is the `ccsi11.dll` in place and does the `ccsi.opt` file reference it?

**Comment by BORE2021** [comment]
Dear author, thank you for your reply. The file you mentioned (ccsi11.dll) is missing, it is not attached in the uploaded file.

**Comment by ksbeattie** [comment]
That file is a separate download, as an asset on the release page.  Here is a direct link to it: [ccsi11.dll](https://github.com/CCSI-Toolset/MEA_ssm/releases/download/3.2.1/ccsi11.dll)

**Comment by BORE2021** [comment]
Dear author, well received, thank you very much for your help.
