### ISSUE TITLE
integration of .dll files

### ISSUE THREAD

**Issue by AureDu** [CCSI-Toolset/MEA_ssm#24]
Hello,
I found the open-source Aspen Plus file named 'CCSI_MEAModel' and I wanted to analyze it but I cannot integrate .dll files into the .bkp one. Can someone help me to do that, please?
Kind regards,
AureDu

**Comment by ksbeattie** [comment]
This was answered via email as follows:

Hello Aure,

Thank you for your interest in these models.

You can find the dll files here under ‘Assets’ on this page: [Release 3.2.1 Release for Aspen v12 · CCSI-Toolset/MEA_ssm · GitHub](https://github.com/CCSI-Toolset/MEA_ssm/releases/tag/3.2.1)

Assuming that you are working in a recent version of Aspen (V11 or later), you will be using the file ‘ccsi11.dll’, and you will just need to make sure the text in the ‘ccsi.opt’ file reads ‘ccsi11.dll’ without the quotations. The opt and dll file should be placed in the same directory as the bkp file, and then you should be able to run the model.

The documentation on this can be found here: [Model Development — MEA Steady-State Model 3.2 documentation](https://mea-ssm.readthedocs.io/en/latest/model_development.html#model-background)

Please let us know if you have any additional questions or issues.

Best regards,
Josh
