### ISSUE TITLE
Property File

### ISSUE THREAD

**Issue by Karim-rabea** [CCSI-Toolset/MEA_ssm#25]
Dear CCSI support team,
I hope you are keeping well.
Many thanks for your huge efforts to build such a helpful model. It is very much appreciated.
I am trying to use the properties impeded in the CCSI model in an Excel file calculation. 
In my attempt to achieve that, I exported the CCSI model as "CCSI_MEAModel.aprbkp", and then started linking the property file to Excel using the Aspen Properties tab as shown in the attached screenshot.

It opens a new file in Aspen Properties Desktop, and while I am in the newly opened property file, I import the previously saved file "CCSI_MEAModel.aprbkp" from the File menu.
To make sure that the compiled codes are working, I defined the location of the library "ccsi11.dll" and the location of the "ccsi.opt" file.
 However, when I run the simulation in the property file, I get this error below.

I was wondering if you could help me address this error, that would be very helpful and much appreciated.

One more question, Could please tell me how I can decompile the CCSI .dll file so I can review the models?
I installed the Intel Fortran Compiler and the MS Visual Studio, but I am still getting the states as an Error.

I apologize for the long message. 
Thank you very much for your help. I deeply appreciate it.
Kind regards

![Aspen Property in Excel](https://github.com/CCSI-Toolset/MEA_ssm/assets/172692727/506a7d27-80d0-473f-b679-629dbce79ee1)
![Error message](https://github.com/CCSI-Toolset/MEA_ssm/assets/172692727/deed068e-061e-498f-baeb-59ace03fd8bb)
![image](https://github.com/CCSI-Toolset/MEA_ssm/assets/172692727/1a683e49-ec68-4cdf-a5be-64dc30326c03)

**Comment by bpaul4** [comment]
Hello @Karim-rabea, it appears that there are two main issues. First, the Fortran Compiler is not installed properly - there should be one option in the console list with a status of "OK". Please consult the online documentation at https://mea-ssm.readthedocs.io/en/latest/index.html and check that the compiler is correctly installed. I recommend that you use Aspen V10 to ensure compatibility with the model. Second, if you are still seeing the error after resolving the compiler installation, I suspect the Excel file that is parsed could contain the non-numeric value.

Per your other question, all of the Fortran subroutine code is included in the online documentation.

Please let me know if you have further questions, or if the error is resolved.

**Comment by bpaul4** [comment]
Hi @Karim-rabea, has the issue been resolved?

**Comment by Karim-rabea** [comment]
Hi Brandon,
Many thanks for your reply. 
I already have Intel Fortran compiler and Microsoft Visual Studio installed on my computer, but I still cannot get any of the status lines as "OK". I will try it on another machine and see how it goes.
Now, that I have connected the CCSI Aspen file to Matlab, hence I can use the model for my case.
Thank you so much, Brandon. I really appreciate your help.
Kind regards
